/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button';
import Alert from '../packages/alert';

const components = [
  Button,
];

const install = function(Vue, opts = {}) {
  // locale.use(opts.locale);
  // locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component)
  })

  Vue.use(Alert);
  // Vue.use(Loading.directive);


  // Vue.prototype.$loading = Loading.service
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  // version: '2.13.2',
  // locale: locale.use,
  // i18n: locale.i18n,
  install,
  Button,
  Alert,
}
